### ISSUE TITLE
이거 코드 누가짬?

### ISSUE THREAD

**Issue by NenkaLab** [DenFade/MineSweeperJS#3]
ㄹㅇ 세계관 최강 병1진들의 코드다

_[FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)을 사용하여 Galaxy S7 Edge에서 보냈습니다_

**Comment by slo0ey** [comment]
야스 뷰지 아트는 xzi가함

**Comment by NenkaLab** [comment]
ㅋㅋㅋㅋㅋㅋ
